# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 09:33
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('CategoryDescription', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('ChargeInvolved', models.BooleanField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Views', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=100)),
                ('Rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsightSupplier.Insight')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('CategoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('CategoryDescription', models.CharField(max_length=1000)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsightSupplier.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('URL', models.URLField()),
                ('Description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='insight',
            name='Categories',
            field=models.ManyToManyField(to='InsightSupplier.SubCategory'),
        ),
        migrations.AddField(
            model_name='insight',
            name='Supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InsightSupplier.Supplier'),
        ),
    ]
