# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InsightSupplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='Category',
        ),
        migrations.AlterField(
            model_name='insight',
            name='Categories',
            field=models.ManyToManyField(to='CommonItems.SubCategory'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='Supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommonItems.Supplier'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
