# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsightSupplier', '0002_auto_20170926_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='Details',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
