# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsightSupplier', '0003_insight_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='Views',
            field=models.BigIntegerField(editable=False),
        ),
    ]
