# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsightSupplier', '0004_auto_20171009_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='Views',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
