# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonItems', '0002_auto_20170927_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='CategoryID',
            field=models.IntegerField(),
        ),
    ]
