# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonItems', '0004_auto_20171017_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='RecentCategories',
            field=models.ManyToManyField(to='CommonItems.SubCategory'),
        ),
    ]
